name: Test FastAPI App

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Test FastAPI app import
      run: |
        cd backend
        python -c "from app.main import app; print('FastAPI app loaded successfully')"
    
    - name: Run basic tests
      run: |
        cd backend
        # 간단한 테스트 - API 서버가 시작되는지 확인
        python -c "
        from app.main import app
        from app.database import engine
        from app.models import Base
        Base.metadata.create_all(bind=engine)
        print('Database tables created successfully')
        "
    
    - name: Check code formatting
      run: |
        cd backend
        # 코드 스타일 체크 (선택사항)
        # pip install black flake8
        # black --check .
        # flake8 .
        echo "Code style check skipped for now"